### ISSUE TITLE
Linker error when using ActionExtension

### ISSUE THREAD

**Issue by shaneosullivan** [promptworks/ignite-action-extension-example#2]
I've been following the instructions for building an Action Extension with React Native at https://www.promptworks.com/blog/building-ios-app-extensions-with-react-native, and everything went fine until the ActionExtension part.

When I create ActionExtension.h and ActionExtension.m, the compilation breaks with the error:

```
Undefined symbols for architecture x86_64:
  "_actionViewController", referenced from:
      -[ActionExtension done] in ActionExtension.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Details: React Native version 0.48.1
XCode Version 8.3.3
I have ensured that ActionExtension.m is built for both targets, as in the instructions.  The problem seems to stem from the fact that ActionExtension.m cannot see the actionViewController property that we have attempted to expose publicly.

My code, in it's current failing-to-build state is on Github at https://github.com/shaneosullivan/ReactNativeExampleBrowserExtension .  The problem can be seen by checking out the code, running `npm install` then trying to build it.

**Comment by shaneosullivan** [comment]
I figured it out.  It turns out that I needed to add `ActionViewController.m` to the compile sources of both targets for it to compile separately.  Perhaps it's worth updating the instructions to say so?

**Comment by patricksmith** [comment]
@shaneosullivan Thanks for reporting back with the fix!

**Comment by swyxio** [comment]
agreed, i faced this too

**Comment by ahtisham09** [comment]
@patricksmith did you fixed this issue

**Comment by ahtisham09** [comment]
@patricksmith can you please update the documentation with latest version of React Native its will really helpful Thanks
